name: Deploy Express App to GCP VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup SSH key
      run: |
        echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > gcp_key
        chmod 600 gcp_key

    - name: Deploy to VM
      run: |
        ssh -o StrictHostKeyChecking=no -i gcp_key ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_IP }} << 'EOF'
          # If node/npm not installed yet:
          sudo apt update
          sudo apt install -y git nodejs npm curl

          # Clone or pull latest
          mkdir -p ~/app
          cd ~/app

          if [ ! -d "server-trucker" ]; then
            git clone https://github.com/Arrnv/server-trucker.git
          fi

          cd server-trucker
          git pull origin main

          # Inject .env
          echo "${{ secrets.ENV_FILE }}" > .env

          # Install dependencies and restart server
          npm install
          npm install -g pm2
          pm2 restart express-server || pm2 start index.js --name express-server
          pm2 save
        EOF
